services:
  dev:
    build: 
      dockerfile: docker/Dockerfile
      context: ..
      ssh:
        - default
      args:
        - USER_ID
    stdin_open: true
    tty: true 
    entrypoint: /bin/bash
    network_mode: host
    restart: always
    ulimits: 
      core: -1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # x11
      - ~/.ssh:/root/.ssh  # ssh
      - ..:/root/kyon_mjlab:rw  # this repo
    environment:
      - TERM=xterm-256color
      - DISPLAY
      - HHCM_FOREST_CLONE_DEFAULT_PROTO=https
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  